services:
  - type: web
    name: cashli
    env: docker
    dockerfilePath: Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@cashli.com
      - key: ADMIN_PASSWORD
        value: Admin@123
      - key: MONGODB_URI
        value: ""
